import './globals.css';
import { Poppins } from 'next/font/google';
import Footer from './components/Footer'; // adjust path if needed

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Shivakumar Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="font-poppins bg-[#0F0F11] text-white">
        <main className="pb-20"> {/* Add padding-bottom to avoid hiding content behind footer */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
